### ISSUE TITLE
Publish the resulting image via GitHub releases

### ISSUE THREAD

**Issue by cipriancraciun** [troglobit/br2-finit-demo#1]
I've been meaning to give `finit` a try, but was looking for a "live image" (CD or disk, or even better kernel/initramfs) to experiment with it.  (And to my knowledge there is no Linux distribution that defaults to `finit`.)  Thus, your build-root could come in handy.

Thus, especially since it is portable, it would be nice to have the resulting image (either kernel+initramfs or disk image) published on GitHub via the releases tab.  Thus whomever wants to try it can just download it and `qemu -kernel ... -initrd ...` and play with it.

**Comment by troglobit** [comment]
Yeah, I've been looking into it.  I'll see what I can do when I release Finit v4.5 (any day now) if I can update this repo and add some downloads.

**Comment by troglobit** [comment]
Fixed in 7611046. 

Latest build now available from https://github.com/troglobit/br2-finit-demo/releases/tag/latest
